services:
  db:
    image: postgres:15-alpine
    container_name: my_academy_quest_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - my_academy_quest_data:/var/lib/postgresql/data

volumes:
  my_academy_quest_data:
